---
#
# tasks file for r2-nodes-cloud-init
# Create the cloud-init for each node
# The idea of having a separate cloud-init for each node is to assign a specific local network IP

## Verify that the RHEL image is present under /var/lib/libvirt/images and fail if not
- name: Verify that the RHEL image is present under /var/lib/libvirt/images and fail if not
  stat: path={{ image_path }}/{{image_rhel8_guest}}
  register: rhelimage_status

#- name: Download {{image_rhel8_guest}}
#  get_url:
#    url: "{{rhel_guest_url}}"
#    dest: "{{ image_path }}/{{ image_rhel8_guest }}"
#    mode: '0440'
#  when: not rhelimage_status.stat.exists

#- name: Install required packages on KVM host (RHEL8)
#  yum:
#    name: "{{ kvm_host8.packages }}"
#   state: latest
# when: ansible_distribution == "RedHat" and ansible_distribution_major_version == '8'

#######################
#   First - get the list of VM running
- name: Get list of vms
  virt: command=list_vms
  register: virt_vms

## Add the libvirt access for the group libvirtd
#- name: Add libvirt access for the group libvirtd
#  lineinfile:
#    path: /etc/libvirt/libvirt.conf
#    line: "{{ item }}"
#    state: present
#  with_items: "{{ libvirt_config_lines }}"


######################################
#
#  Create the underclouds
#  - Undercloud
#  - minion
#
- name: Create VM 
  include: create_vm.yml
  with_items: "{{ vm_name }}"
  when: (item not in virt_vms.list_vms)

# Pause the deployment
#- name: Pause the deployment
#  pause: minutes=5
#  when: undercloud.name not in virt_vms.list_vms
