---
# tasks file for r0-virt-network

# List available networks
- name: List available networks
  virt_net:
    command: list_nets
  register: virt_net_list

- debug: 
    var: virt_ctrlplane
    
#########################################
####### ctlplan virtual network      ####

# if exist, verify the dhcp is disabled
- block:
  # Define a new OSP control plane network
  - name: Define a new network "{{ virt_ctrlplane.name }}" 
    virt_net:
      command: define
      name: "{{ virt_ctrlplane.name }}"
      xml: '{{ lookup("template", "virtnet_ctlplane.xml.j2") }}'
  # Start the network 
  - name: Start the "{{ virt_ctrlplane.name }}" network 
    virt_net:
      command: create
      name: "{{ virt_ctrlplane.name }}"
  # Ensure the OSP control plane network will be started at boot
  - name: 
    virt_net:
      autostart: yes
      name: "{{ virt_ctrlplane.name }}"
  when: (virt_ctrlplane.name not in virt_net_list.list_nets)